In [2]:
import numpy as np


The Basics

In [14]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,4.3,6.2], [2.4,1.8,6.5]])
print(b)

[[9.  4.3 6.2]
 [2.4 1.8 6.5]]


In [7]:
#get dimensions
a.ndim

1

In [9]:
#get shape
b.shape

(2, 3)

In [10]:
a.shape

(3,)

In [15]:
#get data type
a.dtype

dtype('int16')

In [12]:

b.dtype

dtype('float64')

In [16]:
#get size
b.itemsize

8

In [17]:
#get total size
a.nbytes

6

In [18]:
a.size

3

Accessing/changing, specific elemetns, rows, columns, etc.

In [20]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
c.shape

(2, 7)

In [22]:
c[1,4]

12

In [23]:
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
c[: , :3]

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [26]:
c[0, 1:-1:2]

array([2, 4, 6])

In [28]:
c[1,5] = 20
print(c)

c[:, 2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
d[:,0,:]

array([[1, 2],
       [5, 6]])